### PR TITLE
Xcode 8 and Swift 3 migration

### PR DESCRIPTION
**Pull request by vfn**
Xcode 8 and Swift 3 migration

@andreacremaschi you might want to have a look at https://github.com/andreacremaschi/GEOSwift/pull/24 and maybe release a pod version with support to Swift 2.3, and then apply this PR on top of that.

I can do any rebase or change if needed.

### CODE REVIEW

**Comment by vfn** [comment]
@andreacremaschi I had to move away from `xctool` because they will not support `Xcode 8`, or at least don't have plans to do so.

Builds are failing on `iOS 8` and `iOS 10`, due to some issues with `Xcode 8 GM`. Apparently if you use `iPhone SE` it works for `iOS 10`, but I haven't tried it.

**Comment by andreacremaschi** [comment]
Hey @vfn thank you for the PR! I am sorry I can't integrate them myself, I am having some difficulties supporting GEOSwift at the moment, so.. I added you as a collaborator to the project. Feel free to do it if you want! 🍺

**Comment by vfn** [comment]
@andreacremaschi not a problem! I'll handle that. Thanks for the invitation. 🍺

**Comment by andreacremaschi** [comment]
Great! It was a one-man project, now we're a community – of two people, but still :) Thanks for your job, really appreciated

**Comment by vfn** [comment]
Fixes https://github.com/andreacremaschi/GEOSwift/issues/25

**Comment by davidkhess** [comment]
Looking on cocoapods, it still has version 0.4 as latest?

Should we install directly from GitHub?

And thanks for this work!

**Comment by vfn** [comment]
Hi David,

Unfortunately I have not been able to publish tag 0.5 yet. There is an issue with Xcode 8 and the latest stable cocoapods, and when I move to use the prerelease version it fails validating the pod.

Please use it directly from GiHub for the time being, while we sort out the pod problem.

Please let us know if you find any issues integrating it or using it.

**Comment by davidkhess** [comment]
Ok, thanks for the info!

**Pull request merged**
